title       = "Development Tools"
related     = ["text-editors"]

[entry.bindgen]

[entry.rusty-tags]

[entry.clog-cli]

[entry.crate-deps]

[entry.clippy]

[entry.rustup-rs]
crates_io_id = false
homepage_url = "https://www.rustup.rs/"
repository_url = "https://github.com/rust-lang-nursery/rustup.rs"

[entry.dybuk]
crates_io_id = false
repository_url = "https://github.com/Ticki/dybuk"
licence = "MIT"

[entry.rustfmt]

[entry.racer]

[entry.stopwatch]
