title       = "Home Automation"
description = "Home Automation and IoT in Rust."

[entry.mqtt]

[entry.mraa]

[entry.openzwave]

[entry.wemo]

[entry.zwave]
repository_url = "https://gitlab.com/dcuddeback/zwave"
