title       = "Terminal Utilities"
related     = ["text-editors", "development-tools", "ide", "cli-argument-parsers"]

[entry.termsize]

[entry.termion]
crates_io_id = false
repository_url = "https://github.com/ticki/termion"
licence = "MIT"

[entry.ansi_term]

[entry.term-painter]

[entry.colored]

[entry.prettytable-rs]
