title       = "Text Editors"
related     = ["development-tools", "ide"]

[entry.iota]
crates_io_id = "iota-editor"

[entry.sodium]
crates_io_id = false
repository_url = "https://github.com/redox-os/sodium"
licence = "MIT"
